### ISSUE TITLE
Add option to provide one-time policy from user when creating Action

### ISSUE THREAD

**Issue by mszostok** [capactio/capact#329]
## Description

Add field for one-time policy in the Action GraphQL type

Store the one-time policy in a Kubernetes ConfigMap/Secret and store the reference to it in the Action CR

Add optional `--policy` flag to  `capact action create` for providing the one-time policy. In interactive mode, ask if the user wants to provide the policy and open an editor for it.

One-time policy format:
```yaml
rules:
  - interface:
      path: cap.interface.database.postgresql.install
    oneOf:
      - implementationConstraints:
          attributes:
            - path: "cap.attribute.cloud.provider.gcp"
          requires:
            - path: "cap.type.gcp.auth.service-account"
        injectAdditionalInput: {...}
```
