### ISSUE TITLE
`capact ti get` may cause gateway to be oomkilled

### ISSUE THREAD

**Issue by lukaszo** [capactio/capact#415]
## Description

`capact ti get` may cause gateway to be oomkilled. We pull all TypeInstance informations from the API. After running few actions I've got almost 30MB of a raw yaml. 

When this happens, user cannot see any data:

```shell
$ capact ti get
Error: while executing query to list TypeInstances: All attempts fail:
#1: decoding response: invalid character '<' looking for beginning of value
```

Ingress is returning 
```
2021/07/29 13:04:56 >> headers: map[Accept:[application/json; charset=utf-8] Content-Type:[application/json; charset=utf-8]]
2021/07/29 13:05:00 << <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
Because Gateway was killed.

There are few options to solve it:
1. Short term: Increase gateway resources so it's not oomkilled
2. Mid term: Change CLI to query only required data. Fot table view it's only few fields. Problem persists when yaml output is used
3. Long term: All above plus something like pagination so we don't download all

### AC
- Increase gateway resources so it's not oomkilled
- Change CLI to query only required data. Fot table view it's only few fields. Problem persists when yaml output is used

**Comment by mszostok** [comment]
4. It will be also good to think about some cache layer.

**Comment by mszostok** [comment]
**Testing**
I run such test to verify if Gateway component is `OOMKilled`.

1. Create 8 TypeInstances with 1MB payload under `spec.value` via `capact ti stress -r 8 -s 1` (see https://github.com/capactio/capact/pull/443).
2. Build CLI from the latest main (https://github.com/capactio/capact/commit/608679fdce7c449adf7aa82f0b67356fd2c29c25)
3. Execute `capact ti get` result
   ```
   RoundTrip time: 31.028609749s Request size: 3536 Response byte size: 32799137
   ```
  So I was able to fetch 32MB, I also was able to fetch 41MB after adding more TI. The problem was that I had to manually change our HTTP timeout as for 41MB it took 1m5s to download all this data.

Additional problem is that  by adding one TypeInstance with 1MB payload the response body on `capact ti get` is increased by 4MB as we duplicate the `value` multiple times for each `latestResourceVersion`, `firstResourceVersion`, `resourceVersions`, and `resourceVersion(resourceVersion: 1)`. If there will be a new version then it will be duplicated 5times as the `previousResourceVersion` will be also populated.

  * Iterations:
    * From 14mb to 18mb
    * From 18mb to 22mb
    * From 22 to 25mb
    * From 25 to 29mb (first deadline, took more that ~30sec)
    * From 29 to 33mb
    * From 33 to 37mb (took ~60s)
    * From 37 to 41mb (took ~1m5s)

But the gateway was not `OOMKilled` even though  the memory was significantly over the limit for a few secs.
<img width="2045" alt="Screenshot 2021-08-12 at 19 11 12" src="https://user-images.githubusercontent.com/17568639/129331238-9257d5e0-8af9-4029-817e-a1cc4f127f8f.png">

## Memory

Currently, we have such settings:
* gateway: (Change it to 320mb)

  ```yaml
      resources:
        limits:
          cpu: 300m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 48Mi
  ```
* hub-public:

  ```yaml
      resources:
        limits:
          cpu: 400m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 128Mi
  ```
* hub-local:

  ```yaml
      resources:
        limits:
          cpu: 400m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 128Mi
  ```

We can update Gateway
