### ISSUE TITLE
Adjust jinja2 runner to consume multiple input-parameters artifacts and generate single output

### ISSUE THREAD

**Issue by mszostok** [capactio/capact#419]
## Description

Jinja Runner engine can now accept multiple input data files. Now we need to add support for that in our workflows for `jinja2.template` Action execution to consume `N` input-parameters files.

## Reason

Currently, there is no way to easily aggregate output artifacts into a single step.

For example, for [RocketChat ](https://github.com/capactio/hub-manifests/blob/32e1423df7afdfb2060dab99c972750159e1474c/manifests/implementation/rocketchat/install.yaml#L101-L300) we need to execute`jinja.template` 5 times to get final Helm Runner input. This leads to human copy-paste errors and is hard to define, read and maintain.

## Ideas

- Maybe we can use some hacks from map-reduce example:  https://github.com/argoproj/argo-workflows/pull/4175
- Maybe we can produce a `.tgz` file which will be a single input for `jinja2.template`, so we will be able to execute it as
  ```yaml
                - - name: render
                    capact-action: jinja2.template
                    arguments:
                      artifacts:
                        - name: template
                          raw:
                            data: |
                              //...
                        - name: input-parameters
                          from: "{{steps.install-db.outputs.artifacts.mongodb}}"
  ```
  or
  ```yaml
                - - name: zip
                     # our own step where we can define multiple inputs files to be zipped
                     # it's defined by Content Developer, so he can mention as many sources as he wants
                    template: zip-inputs
                    arguments:
                      artifacts:
                        - name: external-url
                          http:
                            url: https://raw.githubusercontent.com/foo/bar.yaml
                        - name: start-yaml
                          from: "{{steps.render-start-yaml.outputs.artifacts.render}}"
                        - name: default-values-yaml
                          from: "{{steps.render-values-yaml.outputs.artifacts.render}}"
                - - name: render
                    capact-action: jinja2.template
                    arguments:
                      artifacts:
                        - name: template
                          raw:
                            data: |
                              //...
                        - name: input-parameters-archive
                          from: "{{steps.zip-inputs.artifacts.output.archive}}"
  ```
- Maybe hack with passing s3 bucket name to `jinja2.template` where all inputs are located
- etc.

## AC
- `jinja2.template` works in a single run on multiple input parameters.
- Current Implementation manifests are simplified based on implemented solution
  Testing:
  - Mock Helm Runner and Terraform Runner to print only input values instead of executing real action
  - Compare printed input values with those before changes. Output should be exactly the same.
