### ISSUE TITLE
The Interface input parameters TypeRef is not populated into Hub

### ISSUE THREAD

**Issue by mszostok** [capactio/capact#426]
## Description

In the task https://github.com/capactio/capact/issues/399 we added new syntax:
```
    parameters:
      input-parameters:
        typeRef:
          path: cap.type.automation.concourse.install-input
          revision: 0.1.0
```
Unfortunately, the populator was not updated and this filed is not populated. We need to update the GraphQL schema: https://github.com/capactio/capact/blob/073d92017457db89731c25302d5e363bc5ac771a/hub-js/graphql/public/schema.graphql#L236-L239

and populator query: https://github.com/capactio/capact/blob/073d92017457db89731c25302d5e363bc5ac771a/pkg/sdk/dbpopulator/populator.go#L113

The models in Go will be automatically updated.
