### ISSUE TITLE
Allow to run any Helm manifest

### ISSUE THREAD

**Issue by lukaszo** [capactio/capact#431]
## Description

If we want to run Helm chart we need to create an Interface and Implementation for it. Sometimes we just want to run Chart in the workload and we don't need/want to have a Interface for it.

I propose to create a generic Helm Interface which can run any Chart.

Running it could look like this:

```yaml

              - - name: run-chart
                  capact-action: helm.install
                  arguments:
                    artifacts:
                      - name: input-parameters
                        raw:
                          data: |
                            chart: bitnami/postgresql
                            repository: https://charts.bitnami.com/bitnami
                            values:
                              value: 1
                              nested:
                                value: 2
```

## Reason

* We don't need Interface/Implementation for every Chart.
* It speeds up the development process

## Questions

1. What would be the output? All values?
