### ISSUE TITLE
Change output.goTemplate in Terraform-based Implementations to be of type string

### ISSUE THREAD

**Issue by mszostok** [capactio/capact#504]
## Description

We had to change the `output.goTemplate` in Helm runner to be a string and not a map. 
To keep it consistent we have to change it also for the Terraform runner and Terraform-based Implementations e.g. `cap.implementation.gcp.cloudsql.postgresql.install`.

## AC
- Change Terraform runner `output.goTemplate` property to string: https://github.com/capactio/capact/blob/main/pkg/runner/terraform/types.go#L36

- Ensure render logic works properly: https://github.com/capactio/capact/blob/main/pkg/runner/terraform/terraform.go#L163-L169
- Modify the Terraform-based Implementations. It should be sufficient to make the following changes:
    ```yaml
    output:
      goTemplate:
        host: "..."
    ```
    to
    ```yaml
    output:
      goTemplate: |
        host: "..."
    ```

## Reason

["Consistent code is easier to maintain, is easier to rationalize, requires less cognitive overhead, and is easier to migrate or update as new conventions emerge or classes of bugs are fixed."](https://github.com/uber-go/guide/blob/master/style.md#be-consistent)

**Comment by mszostok** [comment]
**Issue overview:**

<table>
<tr>
<td> Before </td> <td> After </td>
</tr>
<tr>
<td>

  ```yaml
  output:
    goTemplate:
      host: "{{ .instance_ip_addr }}"
      port: {{ .port }}
      defaultDBName: "{{ .defaultDBName }}"
      superuser:
        username: "{{ .username }}"
        password: "{{ .password }}"
      identifier: "{{ .identifier }}"
      availability_zone: "{{ .availability_zone }}"
      class: "{{ .class }}"
  ```

</td>
<td>

  ```yaml
  output:
    goTemplate: |
      host: "{{ .instance_ip_addr }}"
      port: {{ .port }}
      defaultDBName: "{{ .defaultDBName }}"
      superuser:
        username: "{{ .username }}"
        password: "{{ .password }}"
      identifier: "{{ .identifier }}"
      availability_zone: "{{ .availability_zone }}"
      class: "{{ .class }}"
  ```

</td>
</tr>
</table>

This resolves the rendering issue:

```
while unmarshaling data from file "/terraform-args": error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".port":interface {}(nil)}
```
