### ISSUE TITLE
Add `capact-skip` option for Argo runner

### ISSUE THREAD

**Issue by mszostok** [capactio/capact#509]
## Description

Currently, we are not able to skip a given step. We can only "replace it" - emit other TypeInstance via `capact-when`. 

This requires additional work, and mocking directly in workflow manifests. Additionally, we waste time to execute pods which should be skipped. For example:

Here is an optional step:

```yaml
              - - name: create-sysadmin-secret
                  template: kubectl-create
                  arguments:
                    artifacts:
                      - name: manifest
                        from: "{{steps.create-sysadmin-args.outputs.artifacts.render}}"
```

The template step needs to handle "empty manifests"
```yaml
          # it will use the same serviceAccount as `helm install`
          - name: kubectl-create
            inputs:
              artifacts:
                - name: manifest
                  path: "/in/manifest.yaml"
            outputs:
              artifacts:
                - name: manifest
                  path: "/tmp/manifest.yaml"
            script:
              image: bitnami/kubectl:1.18
              command: [bash]
              source: |
                # Checking if manifest is not empty
                if grep -q '[^[:space:]]' "{{inputs.artifacts.manifest.path}}"; then
                echo "Creating Kubernetes resource..."
                kubectl create -f {{inputs.artifacts.manifest.path}} --output=yaml > {{outputs.artifacts.manifest.path}}
                else
                echo "Creating empty data as the input manifest is empty..."
                cat > "{{outputs.artifacts.manifest.path}}" <<-'EOF'
                metadata:
                  name: ""
                EOF
                fi
```

Instead, we should have:

```yaml
              - - name: create-sysadmin-secret
                  template: kubectl-create
                  capact-skip: {{steps.create-sysadmin-args.outputs.artifacts.render}} == nil
                  arguments:
                    artifacts:
                      - name: manifest
                        from: "{{steps.create-sysadmin-args.outputs.artifacts.render}}"
```
As a result, `kubectl-create` can be simplified to:

```yaml
          - name: kubectl-create
            inputs:
              artifacts:
                - name: manifest
                  path: "/in/manifest.yaml"
            outputs:
              artifacts:
                - name: manifest
                  path: "/tmp/manifest.yaml"
            container:
              image: bitnami/kubectl:1.18
              command: [sh, -c]
              args: ["kubectl create -f {{inputs.artifacts.manifest.path}} --output=yaml > {{outputs.artifacts.manifest.path}}"]
```

Additionally, we should rethink name of the `capact-when` property. This property is more like `replace`, `emit` not `when`.

## Reason

Simplify workflow.
