### ISSUE TITLE
Jinja templating cannot handle dot and square key accessors:

### ISSUE THREAD

**Issue by lukaszo** [capactio/capact#521]
## Description

Jinja templating cannot handle dot and square key accessors:

```yaml
  podAnnotations:
    prometheus.io/port: <@ additionalinput.metrics.podAnnotations["prometheus.io/port"] | default("9121") | tojson @>
    prometheus.io/scrape: <@ additionalinput.metrics.podAnnotations["prometheus.io/scrape"] | default("true") | tojson @>
```

## Expected behavior

It should handle it correctly.

## Actual behavior

It fails with error about not able to access `"prometheus.io/scrape"`. This may be a regression as similar cases where handled in https://github.com/capactio/capact/pull/463

## Steps to reproduce

Just use an example from description.
