### ISSUE TITLE
Additional parameters defined in Workflow policy are not taken into account 

### ISSUE THREAD

**Issue by mszostok** [capactio/capact#536]
## Description

Base on our Workflow Policy syntax I defined such step:
```yaml
              - - name: rocketchat-install
                  capact-action: rocketchat.install
                  capact-policy:
                    rules: # Configures the following behavior for Engine during rendering Action for this step
                      - interface: # Rules for Interface with exact path
                          path: cap.interface.productivity.rocketchat.install
                        oneOf:
                          - implementationConstraints: # Find and use an Implementation which:
                              path: "cap.implementation.rocketchat.install"
                            inject:
                              additionalParameters: # Injects additional parameters for the Implementation
                                - name: additional-parameters # Name must match one of the parameter defined under additionalInput.parameters in the Implementation
                                  value:
                                    ingress:
                                      enabled: false
```

Unfortunately the values were not injected into a given implementation.

Using exactly the same policy but as an Action Policy works properly and artifact is injected:

```yaml
                  - name: additional-parameters
                    raw:
                      data: |
                        ingress:
                          enabled: false
```

## Steps to reproduce

1. Create umbrella workflow with such step:
  ```yaml
                - - name: rocketchat-install
                    capact-action: rocketchat.install
                    capact-policy:
                      rules: # Configures the following behavior for Engine during rendering Action for this step
                        - interface: # Rules for Interface with exact path
                            path: cap.interface.productivity.rocketchat.install
                          oneOf:
                            - implementationConstraints: # Find and use an Implementation which:
                                path: "cap.implementation.rocketchat.install"
                              inject:
                                additionalParameters: # Injects additional parameters for the Implementation
                                  - name: additional-parameters # Name must match one of the parameter defined under additionalInput.parameters in the Implementation
                                    value:
                                      ingress:
                                        enabled: false
  ```
2. Upload manifests to Hub
3. Execute action
4. Check rendered manifest. It doesn't have the params, even though the proper implementation has been selected. 
   ```yaml
                  - name: additional-parameters
                    raw:
                      data: |
                        ingress:
                          enabled: false
   ```
