### ISSUE TITLE
Support setting relations for optional TypeInstances in workflows

### ISSUE THREAD

**Issue by mszostok** [capactio/capact#537]
## Description

Support setting relations for optional TypeInstances in workflows. Currently, we cannot set the relations for TypeInstance that may be not available. We can define them as `additionalInput.typeInstances` but cannot create relations for them.

Currently we will get panic in case doing that.

## Reason

This will be useful for rollback operation and also for knowing the relations between available components

## Use cases

1. Content Developer - will be able to better describe relations between created resources
2. System User  and System Administrator - have better discoverability where a given application were installed. Currently, they don't know on which cluster they are running.

Example use-case:

Allow to install applications on external cluster and tight them to proper kubeconfig and cluster TypeInstances

  Define additional input:
  ```yaml
    additionalInput:
      typeInstances:
        kubeconfig:
          typeRef:
            path: cap.type.containerization.kubernetes.kubeconfig
            revision: 0.1.0
          verbs: [ "get" ]
  ```
  
  Create optional relation:
  ```yaml
    outputTypeInstanceRelations:
      rocketchat-config:
        uses:
          - rocketchat-helm-release
          - mongodb
         # Here we can create optional relation if kubeconfig will be provided and a Rocket.Chat will be finally installed on different cluster.
          - kubeconfig
  ```
