### ISSUE TITLE
We cannot pass optional TypeInstance defined in `additionalInput.typeInstances` in the umbrella workflows.

### ISSUE THREAD

**Issue by mszostok** [capactio/capact#538]
## Description

We cannot pass optional TypeInstance defined in `additionalInput.typeInstances` from the umbrella workflows.

#### Example

Define an umbrella workflow which creates e.g. PostgreSQL and wants to pass this database to the next steps, e.g. Concourse install and Rocket.Chat install. As a result those applications shares the same db.

In normal situation we do that via Policy but this is not supported in Workflow Policy.  We also cannot pass it via artifacts, because if it will be missing, the relation cannot be created and this causes panic in render logic.

It's bug in our design and also in our engine as passing optional TypeInstance as artifacts will cause panic in renderer:

  ```yaml
  - - name: concourse-install
      capact-action: concourse.install
      arguments:
        artifacts:
          - name: input-parameters
            from: "{{inputs.artifacts.input-parameters}}"
          - name: kubeconfig
            from: "{{steps.create-target-cluster.outputs.artifacts.kubeconfig}}"
       # here we cannot pass optional TI
         - name: postgresql
           optional: true
  ```

   results in such panic:
   ```go
   2021-10-20T09:52:09.411Z        INFO    policy-svc      policy/service.go:82    Getting Policy  {"module": "policyService"}
   panic: runtime error: invalid memory address or nil pointer dereference
   [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x180db31]
   
   goroutine 485 [running]:
   capact.io/capact/pkg/sdk/renderer/argo.(*TypeInstanceHandler).AddUploadTypeInstancesStep(0xc000c95e18, 0xc0006d4780, 0xc00098af00, 0xc000455c20, 0x2f, 0x0, 0x0)
           /capact.io/capact/pkg/sdk/renderer/argo/typeinstance_handler.go:162 +0x611
   capact.io/capact/pkg/sdk/renderer/argo.(*dedicatedRenderer).AddOutputTypeInstancesStep(0xc000594180, 0xc0006d4780, 0xc000666fc0, 0xc0006d4780)
           /capact.io/capact/pkg/sdk/renderer/argo/dedicated_renderer.go:138 +0x73
   capact.io/capact/pkg/sdk/renderer/argo.(*Renderer).Render(0xc000673d80, 0x202c6c8, 0xc0004ad0b0, 0xc00018d270, 0x0, 0x0, 0x0)
           /capact.io/capact/pkg/sdk/renderer/argo/renderer.go:191 +0xea9
   capact.io/capact/internal/k8s-engine/controller.(*ActionService).RenderAction(0xc0006f8be0, 0x202c6c8, 0xc0004ad0b0, 0xc0006323c0, 0x0, 0x0, 0x0)
           /capact.io/capact/internal/k8s-engine/controller/action_service.go:399 +0x583
   capact.io/capact/internal/k8s-engine/controller.(*ActionReconciler).renderAction(0xc000184540, 0x202c6c8, 0xc0004ad0b0, 0xc0006323c0, 0x0, 0x0, 0x2, 0x2054320)
           /capact.io/capact/internal/k8s-engine/controller/action_controller.go:197 +0x73
   capact.io/capact/internal/k8s-engine/controller.(*ActionReconciler).Reconcile(0xc000184540, 0x202c6c8, 0xc0004ad0b0, 0xc000d37430, 0x7, 0xc000d37420, 0x2, 0xc0004ad0b0, 0xc00003a000, 0x1c0f9e0, ...)
           /capact.io/capact/internal/k8s-engine/controller/action_controller.go:137 +0x905
   sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0006f8c80, 0x202c620, 0xc000927680, 0x1bae5c0, 0xc000d71fe0)
           /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:298 +0x30d
   sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0006f8c80, 0x202c620, 0xc000927680, 0x0)
           /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:253 +0x205
   sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc000a79290, 0xc0006f8c80, 0x202c620, 0xc000927680)
           /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:214 +0x6b
   created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
           /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:210 +0x425
   ```

## Ideas

This can be solved by: https://github.com/capactio/capact/issues/539
