### ISSUE TITLE
Validate TypeInstance input during TypeInstance creation

### ISSUE THREAD

**Issue by lukaszo** [capactio/capact#544]
## Description

I've created `cap.type.database.object.aws.s3.config` with a typo in `accesskey` and TypeInstance was created without any problems.

Support:
- CLI 
- Argo Actions TypeInstance upload - in workflow

Make sure all manifests are valid (that TypeInstance upload always succeeds as the data is valid)

## Expected behavior

I've should get an error about missing `accesskey` key.

## Actual behavior

No error was returned.

## Steps to reproduce

Define TypeInstance:

```yaml
typeInstances:
  - alias: aws-s3
    attributes:
      - path: cap.attribute.cloud.provider.aws
        revision: 0.1.0
    typeRef:
      path: cap.type.database.object.aws.s3.config
      revision: 0.1.0
    value:
      accessKey: aaaaa
      endpoint: https://s3.amazonaws.com
```

There is typo in `accessKey` it should be `accesskey`. Also, `secretkey` is missing.
