### ISSUE TITLE
Helm generator generates invalid Helm runner arguments for empty objects and arrays

### ISSUE THREAD

**Issue by pkosiec** [capactio/capact#663]
## Description

The command `capact manifest generate implementation helm ...`, as well as the interactive `capact manifest generate` commands, generate invalid input arguments for Helm runner, when there are empty objects and arrays inside `values.yaml` file.

## Expected behavior

For the following values.yaml:

```yaml
imagePullSecrets: []
podAnnotations: {}
podSecurityContext: {}
nodeSelector: {}
```

The result should be:

```yaml
imagePullSecrets: <@ additionalinput.imagePullSecrets | default([]) | tojson @>
nodeSelector: <@ additionalinput.nodeSelector | default({}) @>
podAnnotations: <@ additionalinput.podAnnotations | default({}) @>
podSecurityContext: <@ additionalinput.podSecurityContext | default({}) @>
```

And for each object, we should include `additionalParameters: true` in JSON schema to highlight, that there might be custom properties to define.

## Actual behavior

```yaml
imagePullSecrets: <@ additionalinput.imagePullSecrets | default(None) | tojson @>
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
```

where the `default(None) | tojson` jinja2 renders to `null`, and JSON schema says by default it is empty array:

```json
"imagePullSecrets": {
    "type": "array",
    "title": "ImagePullSecrets",
    "default": [],
    "$id": "#/properties/imagePullSecrets"
},
```

Also, an empty object is rendered as:

```json
"nodeSelector": {
    "properties": {},
    "type": "object",
    "title": "NodeSelector",
    "$id": "#/properties/nodeSelector"
},
```

so, according to JSON schema, you cannot define any properties.

## Steps to reproduce

Generate manifests:

```bash
capact manifest generate implementation helm cap.implementation.secret-storage-backend.install ./deploy/kubernetes/charts/secret-storage-backend -o /tmp/generated
```

See the generated Implementation manifest:

```bash
cat /tmp/generated/implementation/secret-storage-backend/install.yaml
```

Observe the following:

```yaml
imagePullSecrets: <@ additionalinput.imagePullSecrets | default(None) | tojson @>
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
```

Instead of:

```yaml
imagePullSecrets: <@ additionalinput.imagePullSecrets | default([]) | tojson @>
nodeSelector: <@ additionalinput.nodeSelector | default({}) @>
podAnnotations: <@ additionalinput.podAnnotations | default({}) @>
podSecurityContext: <@ additionalinput.podSecurityContext | default({}) @>
```
