### ISSUE TITLE
Adjust all Implementation manifests to use latest workflow syntax and storage backends

### ISSUE THREAD

**Issue by pkosiec** [capactio/capact#666]
## Description

Blocked by #634, #650, #665

- Adjust all Implementation manifests inside `capactio/hub-manifests` to use the latest workflow syntax (Argo workflows artifact content) - breaking change introduced in #634 
- Use Helm storage for all Helm installation (introduced in #650)
- Use dynamic TypeInstance projection for output TypeInstances (#665 and #650)
- Update RocketChat and Mattermost installation tutorial (add prerequisite for Helm storage)

**Additional scope:**
- Move outputting static Helm Release logic from Helm Runner inputs to env variables
- Remove `output.useHelmReleaseStorage` from `helm.install` and add env variable to Helm Runner container. We have now two Implementations (`install` and `install-static`, so we can distinguish them). However, all manifests that use Helm runner should be updated to always assume they use the new `helm.install` which outputs dynamic Helm Release TI. That means:

```yaml
capact-outputTypeInstances:
  - name: helm-release
     from: helm-release
```

Needs to be changed to:

```yaml
capact-outputTypeInstances:
  - name: helm-release
     from: helm-release
     backend: helm-release-storage # from requires section
```

- Remove `output.useHelmReleaseStorage` from `helm.upgrade` input Type - detect input TypeInstance in Helm Runner and output the same shape
- Consider making a dedicated Interface and Implementation for the `ti-value-fetcher`.

Timebox for 3SP.

## Related issues

See epic https://github.com/capactio/capact/issues/604 for reason and use cases.
